### ISSUE TITLE
Buttons for items on the screen affect the index before them.

### ISSUE THREAD

**Issue by Koulis2000** [Koulis2000/OCScripts#17]
When clicking the selected/minus/plus buttons, the items affected are the above the desired. I am not sure which part of the code affects that. It seems like it's caused in waltz, maybe the way it checks for user input?

**Comment by Bjonnfesk** [comment]
I suspect it is this method:

https://github.com/Bjonnfesk/Waltz/blob/1c8533c8358be87d66eac94f73aacc39f7614ab6/waltz.lua#L192-L222

I left a computer near the town hall. If you make sure there is an active build request, and restart the program `colonel` running on it, you should be able to click the buttons... _if_ you click the bottom line of each button. That should open a popup-Panel. The Close button in the popup doesn't seem to work even you press the bottom line. Thus, the flaw in the detection method is probably affected by the properties of the parent component.

**Comment by Bjonnfesk** [comment]
I remember that figuring out which component was clicked based on the coordinates of the click was a serious challenge. 
The reason is that you may click somewhere that is a `Button`, but the `Button` is inside a `Panel`. If the `Panel` was added (with `Waltz:addComponent()`) _before_ the `Button`, the program will think you clicked the `Panel`. Therefore, `Waltz:getComponentAt()` has to call itself recursively, but this time it will search for which `Button` _inside_ the `Panel` occupies the position you clicked. This recursion could go many layers deep before we find a `Button`.
Apparently, I never overcame that challenge.

It's hard to keep straight whether you need to be using absolute coordinates or relative coordinates, etc. etc.

**Comment by Koulis2000** [comment]
Can the panel be ignored in some way? Except for extreme case, I'm not sure if we'd ever make a clickable panel.

**Comment by Bjonnfesk** [comment]
The problem has nothing to do with clickable `Panel`s. They are not clickable in any real sense. 

The thing is that when the UI looks for the component that was clicked, it first looks in itself. It then finds that the pixel that was clicked belongs to a `Panel`. Now, it has to look for which component inside the `Panel` was clicked, precisely because `Panel`s are not clickable. This is how a `Panel` can pass a click through itself and into its child components.

**Comment by Koulis2000** [comment]
Okay I see.

**Comment by Bjonnfesk** [comment]
https://github.com/Bjonnfesk/Waltz/issues/4

Actually this issue. Closing this one and using the one in the Waltz repo to track from now on.
